import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.184.0/build/three.module.js';
const urls={1:'https://raw.githubusercontent.com/licdiego2710-create/CLAUDE/main/alondra-diego-1-6m/sprite1.svg',2:'https://raw.githubusercontent.com/licdiego2710-create/CLAUDE/main/alondra-diego-1-6m/sprite2.svg',3:'https://raw.githubusercontent.com/licdiego2710-create/CLAUDE/main/alondra-diego-1-6m/sprite3.svg',4:'https://raw.githubusercontent.com/licdiego2710-create/CLAUDE/main/alondra-diego-1-6m/sprite4.svg',5:'https://raw.githubusercontent.com/licdiego2710-create/CLAUDE/main/alondra-diego-1-6m/sprite5.svg'};
const canvas=document.getElementById('scene'),mobile=innerWidth<820,renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.2:1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xf9eef1,mobile?.018:.022);const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,150);camera.position.z=12;
scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.PointLight(0xffb6ca,28,40);light.position.set(4,4,10);scene.add(light);
const loader=new THREE.TextureLoader(),planes=[];
for(let i=0;i<26;i++){let g=Math.floor(i/6)+1,s=i%6,c=s%3,r=Math.floor(s/3);loader.load(urls[g],base=>{let t=base.clone();t.needsUpdate=true;t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(1/3,1/2);t.offset.set(c/3,r?0:1/2);let m=new THREE.Mesh(new THREE.PlaneGeometry(mobile?2.6:4.2,mobile?3.45:3.15),new THREE.MeshBasicMaterial({map:t,transparent:true,opacity:.92,side:THREE.DoubleSide}));let side=i%2?-1:1;m.position.set(side*(mobile?1.35+Math.random()*.35:3.1+Math.random()*1.2),(Math.random()-.5)*(mobile?2.2:4),-2-i*(mobile?4.3:6));m.rotation.set(0,side*(mobile?.07:.14),(Math.random()-.5)*(mobile?.08:.16));m.userData.y=m.position.y;m.userData.p=Math.random()*6.28;scene.add(m);planes.push(m)})}
const count=mobile?260:600,a=new Float32Array(count*3);for(let i=0;i<count;i++){a[i*3]=(Math.random()-.5)*22;a[i*3+1]=(Math.random()-.5)*15;a[i*3+2]=10-Math.random()*100}let pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(a,3));scene.add(new THREE.Points(pg,new THREE.PointsMaterial({color:0xeab3c1,size:.035,transparent:true,opacity:.34})));
let sx=0,sy=0,target=0,smooth=0;addEventListener('pointermove',e=>{sx=(e.clientX/innerWidth-.5)*2;sy=(e.clientY/innerHeight-.5)*2},{passive:true});addEventListener('scroll',()=>{let a=document.getElementById('album'),max=Math.max(1,a.offsetTop-innerHeight);target=Math.min(1,scrollY/max)},{passive:true});
let clock=new THREE.Clock();function loop(){let t=clock.getElapsedTime();smooth+=(target-smooth)*.055;camera.position.z=12-smooth*(mobile?50:105);camera.position.x+=(sx*(mobile?.35:.9)-camera.position.x)*.035;camera.position.y+=(-sy*(mobile?.25:.6)-camera.position.y)*.035;planes.forEach(m=>{m.position.y=m.userData.y+Math.sin(t*.45+m.userData.p)*.12;let d=Math.abs(camera.position.z-m.position.z);m.material.opacity=THREE.MathUtils.clamp(1.1-d/28,.12,.94)});renderer.render(scene,camera);requestAnimationFrame(loop)}loop();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});